const tg=window.Telegram?.WebApp; if(tg){tg.ready();tg.expand();}
const user=tg?.initDataUnsafe?.user; let xp=120;
const lessons=[['Konstitutsiyaviy huquq','Davlat, inson huquqlari va konstitutsiyaviy kafolatlar'],['Fuqarolik huquqi','Mulk, shartnoma va majburiyatlar'],['Mehnat huquqi','Xodim va ish beruvchi huquqlari'],['Oila huquqi','Nikoh, oila va ota-ona majburiyatlari'],['Iste’molchi huquqi','Xarid va xizmatlarda huquqlaringiz']];
const app=document.querySelector('#app');
function home(){app.innerHTML=`<section class="hero"><small>HUQUQON • HUQUQIY SAVODXONLIK</small><h1>Salom, ${user?.first_name||'foydalanuvchi'} 👋</h1><p>Huquqni yodlamang — tushuning va hayotda qo‘llang.</p><span class="pill">🔥 3 kunlik faollik</span></section><section class="card" style="margin-top:14px"><b>Huquqiy darajangiz</b><p class="muted">${xp} XP · Boshlang‘ich tadqiqotchi</p><div class="progress"><i></i></div></section><div class="grid"><div class="card"><b>📚 Akademiya</b><p class="muted">Tizimli darslar</p></div><div class="card"><b>🧠 Testlar</b><p class="muted">Bilimni sinash</p></div><div class="card"><b>🛡️ Huquqim</b><p class="muted">Hayotiy vaziyatlar</p></div><div class="card"><b>🤖 AI yordamchi</b><p class="muted">Manbali yo‘naltirish</p></div></div><section class="card" style="margin-top:14px"><small class="gold">KUN HUQUQI</small><h3>Shaxsiy hayot daxlsizligi</h3><p class="muted">Huquqning mazmuni, real misol va rasmiy manba bir joyda beriladi.</p></section>`}
function learn(){app.innerHTML=`<h2>⚖️ HuquqON Akademiya</h2><p class="muted">Talaba va fuqarolar uchun ikki darajali o‘quv tizimi.</p><div class="list">${lessons.map((x,i)=>`<div class="card" onclick="lesson(${i})"><span class="pill">MODUL ${i+1}</span><h3>${x[0]}</h3><p class="muted">${x[1]}</p></div>`).join('')}</div>`}
window.lesson=i=>{let x=lessons[i];app.innerHTML=`<button class="primary" onclick="learn()">← Ortga</button><section class="card" style="margin-top:14px"><span class="pill">DARS</span><h2>${x[0]}</h2><p class="muted">${x[1]}. Yakuniy versiyada har bir dars: sodda tushuncha → real misol → huquqiy norma → kazus → mini-test → rasmiy manba shaklida bo‘ladi.</p><h3>💡 Hayotiy misol</h3><p class="muted">Nazariya real vaziyat bilan bog‘lanadi. Foydalanuvchi nima uchun bu norma kerakligini tushunadi.</p><button onclick="xp+=20;home()">Darsni yakunlash · +20 XP</button></section>`}
function rights(){app.innerHTML=`<h2>🛡️ Mening huquqim</h2><p class="muted">Muammoni tanlang. Tizim harakat algoritmini ko‘rsatadi.</p><div class="list">${['Ish haqim berilmadi','Nuqsonli mahsulot sotib oldim','Ta’lim olish huquqim buzildi','Shaxsiy ma’lumotim tarqaldi'].map(x=>`<div class="card"><h3>${x}</h3><p class="muted">Vaziyat → dalillar → huquqiy asos → qayerga murojaat qilish.</p><button onclick="alert('Keyingi bosqichda bu modul rasmiy huquqiy manbalar bilan ulanadi.')">Yo‘l-yo‘riq</button></div>`).join('')}</div>`}
function profile(){app.innerHTML=`<section class="hero"><small>PROFIL</small><h2>${user?.first_name||'HuquqON foydalanuvchisi'}</h2><p>${xp} XP · 3 kunlik faollik</p></section><div class="grid"><div class="card"><b>5</b><p class="muted">Dars</p></div><div class="card"><b>72%</b><p class="muted">Test</p></div><div class="card"><b>3</b><p class="muted">Yutuq</p></div><div class="card"><b>4</b><p class="muted">Saqlangan</p></div></div>`}
const pages={home,learn,rights,profile};document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>pages[b.dataset.page]());home();
